/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface EventCardProps {
  date: string;
  title: string;
  time: string;
  location: string;
}

const EventCard: React.FC<EventCardProps> = ({
  date,
  title,
  time,
  location,
}) => {
  return (
    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex overflow-hidden flex-col pb-4 mx-auto w-full leading-none text-blue-900 bg-white rounded-3xl border border-solid border-white border-opacity-20 shadow-[0px_4px_12px_rgba(0,56,140,0.1)] max-md:mt-7">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/02f7c504e127ea438567b6a18bdbaec5ddcc5ef6b3619044f40878aea138e02e?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          alt=""
          className="object-contain w-full aspect-[3.11]"
        />
        <div className="flex gap-10 justify-between items-center mx-4 mt-5 max-md:mx-2.5">
          <div className="flex gap-4 self-stretch my-auto rounded-lg w-[207px]">
            <div className="flex flex-col justify-center items-center p-2 font-semibold text-center uppercase whitespace-nowrap rounded-lg bg-blue-900 bg-opacity-20 min-h-[66px]">
              <div className="text-sm">{date.split(" ")[0]}</div>
              <div className="mt-1 text-3xl">{date.split(" ")[1]}</div>
            </div>
            <div className="flex flex-col my-auto">
              <div className="text-base font-semibold max-md:mr-2">{title}</div>
              <div className="mt-1 text-xs">
                {time} · {location}
              </div>
            </div>
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f4411a9db7e47a3005a1a677889431926a9a0f347099416cd304bc6229a9003f?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto aspect-[1.76] w-[60px]"
          />
        </div>
      </div>
    </div>
  );
};

export default EventCard;
