/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TokenCard from "./TokenCard";
import EventCard from "./EventCard";

interface MainContentProps {
  children: React.ReactNode;
}

const tokenData = [
  {
    value: "$1000 token",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7e1061d06a3d993675dc5b46cf7161b6c0d358a3ffa75ae0da10c2322f3cc95c?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    value: "$990 token",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/1af8e7a77b08be2c324fee1a236064c5364644285d610fe93044e1a304b7bc9d?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    value: "$989 token",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e1926d8d15b3ae3920f55a0e88de579742269a2fe9e5b413a7aabbfa39bca913?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
];

const eventData = [
  {
    date: "Apr 20",
    title: "UI-Design Session",
    time: "Thu 10:15",
    location: "New York, NY",
  },
  {
    date: "Apr 20",
    title: "UI-Design Session",
    time: "Thu 10:15",
    location: "New York, NY",
  },
  {
    date: "Apr 20",
    title: "UI-Design Session",
    time: "Thu 10:15",
    location: "New York, NY",
  },
  {
    date: "Apr 20",
    title: "UI-Design Session",
    time: "Thu 10:15",
    location: "New York, NY",
  },
  {
    date: "Apr 20",
    title: "UI-Design Session",
    time: "Thu 10:15",
    location: "New York, NY",
  },
  {
    date: "Apr 20",
    title: "UI-Design Session",
    time: "Thu 10:15",
    location: "New York, NY",
  },
];

const MainContent: React.FC<MainContentProps> = ({ children }) => {
  return (
    <main className="flex flex-col ml-5 w-[79%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col self-stretch my-auto w-full max-md:mt-10 max-md:max-w-full">
        <div className="w-full max-w-[1062px] max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            {tokenData.map((token, index) => (
              <TokenCard key={index} value={token.value} icon={token.icon} />
            ))}
          </div>
        </div>
        <div className="flex flex-col pl-1.5 mt-14 w-full max-md:mt-10 max-md:max-w-full">
          <h2 className="self-start text-xl font-medium text-black max-md:max-w-full">
            Participate in event to network with expert and earn coin !
          </h2>
          <div className="mt-7 max-md:max-w-full">
            <div className="flex gap-5 flex-wrap">
              {eventData.map((event, index) => (
                <EventCard
                  key={index}
                  date={event.date}
                  title={event.title}
                  time={event.time}
                  location={event.location}
                />
              ))}
            </div>
          </div>
        </div>
      </div>
      {children}
    </main>
  );
};

export default MainContent;
