/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface NavItemProps {
  icon: string;
  label: string;
}

const NavItem: React.FC<NavItemProps> = ({ icon, label }) => {
  return (
    <div className="flex gap-2.5 px-3.5 py-2.5 rounded-md border-white border-l-[5px]">
      <img
        loading="lazy"
        src={icon}
        alt=""
        className="object-contain shrink-0 my-auto w-5 aspect-square"
      />
      <div className="flex-1 shrink basis-0">{label}</div>
    </div>
  );
};

export default NavItem;
