/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SettingsItemProps {
  icon: string;
  label: string;
}

const SettingsItem: React.FC<SettingsItemProps> = ({ icon, label }) => {
  return (
    <div className="flex overflow-hidden gap-2.5 px-3.5 py-2.5 mt-2 rounded-md min-h-[39px]">
      <img
        loading="lazy"
        src={icon}
        alt=""
        className="object-contain shrink-0 my-auto w-5 aspect-square"
      />
      <div className="flex-1 shrink basis-0">{label}</div>
    </div>
  );
};

export default SettingsItem;
