/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NavItem from "./NavItem";
import SettingsItem from "./SettingsItem";

const navItems = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8c5c232620efa12614b00360cb6c51636dc8a2ee8ccbd9ede41923b6c3c722c6?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Home",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8c5c232620efa12614b00360cb6c51636dc8a2ee8ccbd9ede41923b6c3c722c6?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Dashboard",
  },
];

const academicItems = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6ece77d92f51d44a6279c045af054effd223722fce99ffa01d1be3c7e6f2ed7e?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "New Skill",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b2ce1294b5b240f52b6b43b7ebf20661fb5241b79eeeba12a36eb11df0c37d7a?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Expert",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/ed4bacc144346ab2e7147932a690d8185d0ae827ea6f742201694d6a2ca7f461?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Progress",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/88e47e2de1bf29fc3247baa4ebb25e8993e2b147082b11e9bafa00cbe15f44ea?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Chat",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/eed4648a734703a610f65e0537b5c71f41f30a8c4ca85f1c959e49f2b441049d?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Announcements",
  },
];

const settingsItems = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/cc3d06843728db0f3367d3318c4c6b497b86cad43bd9aa80951e2e72a07e87af?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Account settings",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/ef320a2e7b16f6b98e71f92da8ac8a0996f3188def692317a7625c9fb3f52128?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Notification preferences",
  },
];

const Sidebar: React.FC = () => {
  return (
    <aside className="flex flex-col w-[21%] max-md:ml-0 max-md:w-full">
      <nav className="flex overflow-hidden flex-col grow w-full text-base font-semibold text-white bg-white border-r border-neutral-200 max-md:mt-7">
        <div className="flex overflow-hidden flex-col bg-white border-r border-neutral-200">
          <div className="flex flex-col items-start pt-7 pr-1.5 pb-24 w-full bg-slate-900 rounded-[76px]">
            <div className="flex-1 shrink gap-2.5 px-3.5 py-2.5 whitespace-nowrap rounded-md border-white border-l-[5px]">
              Home
            </div>
            <div className="z-10 flex-1 shrink gap-2.5 px-3.5 py-2.5 mt-0 whitespace-nowrap rounded-md border-white border-l-[5px]">
              Home
            </div>
            <h1 className="z-10 -mt-6 ml-4 text-3xl tracking-tight text-zinc-100 max-md:ml-2.5">
              Skill³
            </h1>
            <div className="flex flex-col self-stretch mt-14 w-full text-xl font-medium max-md:mt-10">
              <div className="flex flex-col items-start pr-12 pl-5 w-full font-semibold whitespace-nowrap max-md:pr-5">
                {navItems.map((item, index) => (
                  <NavItem key={index} icon={item.icon} label={item.label} />
                ))}
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/65202168aab88bd2cf4b3af333e951f187227c9112e2247883e1fce288a30599?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain mt-5 w-full max-md:mr-1.5"
              />
              <div className="flex flex-col items-start px-5 mt-7 w-full max-md:pr-5">
                <div>ACADEMIC</div>
                {academicItems.map((item, index) => (
                  <NavItem key={index} icon={item.icon} label={item.label} />
                ))}
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/8079025b46cd1b9dfeb24fbd326b42c400a6d7451fde99f64b29efbe285fe46e?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain mt-1.5 w-full aspect-[250]"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/82a6eb4b486b708b34f6a447b8d0ce8a768261f2d9881380e1424491516f0011?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain self-start mt-36 w-full aspect-[250] max-md:mt-10"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/72bee63fa8fd87abb25256e4f3077a34a8b9dc39da988e0bc5a1c7b6b353dbb3?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain mt-3.5 w-full aspect-[250]"
              />
              <div className="flex flex-col items-start pr-9 pl-2.5 mt-1.5 w-full text-base max-md:pr-5">
                <div className="ml-3 text-base max-md:ml-2.5">SETTINGS</div>
                {settingsItems.map((item, index) => (
                  <SettingsItem
                    key={index}
                    icon={item.icon}
                    label={item.label}
                  />
                ))}
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/806a62aeab22292b8114173ff0bb3945f7808ce63a80aedcc06ae9b5dc5a97c2?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain self-start mt-6 w-full aspect-[250]"
              />
              <div className="flex overflow-hidden gap-2.5 self-start px-3.5 py-2.5 mt-4 text-base whitespace-nowrap min-h-[39px] max-md:ml-2.5">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/f6ba7d8fb5268aad68ba0c588b51bea8864f5f382c894f505dffee5d7cd03357?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                  alt=""
                  className="object-contain shrink-0 my-auto w-5 aspect-square"
                />
                <div className="flex-1 shrink basis-0">Logout</div>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </aside>
  );
};

export default Sidebar;
