/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface TokenCardProps {
  value: string;
  icon: string;
}

const TokenCard: React.FC<TokenCardProps> = ({ value, icon }) => {
  return (
    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex grow max-md:mt-10">
        <div className="flex flex-col items-start p-4 mr-0 w-full rounded-2xl shadow-sm bg-[linear-gradient(134deg,#4E4E4E_-16.04%,#333_9.33%,#1A1A1A_32.02%,#1A1A1A_62.06%,#262626_87.42%,#4E4E4E_112.12%)]">
          <div className="flex gap-3 justify-center items-center">
            <div className="flex gap-2.5 items-center self-stretch p-2 my-auto bg-emerald-300 rounded-lg h-[38px] w-[38px]">
              <div className="flex w-6 min-h-[24px]" />
            </div>
            <div className="flex gap-1.5 justify-center items-center self-stretch my-auto">
              <div className="self-stretch my-auto text-xs font-medium leading-snug text-emerald-400">
                +32.40%
              </div>
              <div className="flex gap-2.5 items-center self-stretch p-0.5 my-auto rounded-3xl bg-green-300 bg-opacity-20 h-[18px] w-[18px]">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/4c2e4e283646c8df685795c9116523cde9c8c378fa84a8604d7b6d2b2f21c0f0?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                  alt=""
                  className="object-contain w-3.5 aspect-square"
                />
              </div>
            </div>
          </div>
          <div className="flex flex-col mt-2">
            <div className="text-3xl font-semibold leading-snug text-white">
              {value}
            </div>
            <div className="mt-2 text-sm font-medium leading-tight text-indigo-400">
              Best candidate
            </div>
          </div>
        </div>
        <img
          loading="lazy"
          src={icon}
          alt=""
          className="object-contain shrink-0 self-start mt-4 aspect-square w-[42px]"
        />
      </div>
    </div>
  );
};

export default TokenCard;
